### ISSUE TITLE
Issues with Blender 3.6 (A mesh with name Cube already exists.)

### ISSUE THREAD

**Issue by techdragon** [CodeToCAD/CodeToCAD#182]
```
Python: Traceback (most recent call last):
  File "/var/folders/xg/tljx53lx3lx9hmdt29t03nf40000gn/T/1692334237.blend/Text", line 6, in <module>
  File "/Users/techdragon/Library/Application Support/Blender/3.6/scripts/addons/CodeToCADBlenderAddon/BlenderProvider.py", line 590, in createCube
    return self._createPrimitive("cube", "{},{},{}".format(width, length, height), **(keywordArguments or {}))
  File "/Users/techdragon/Library/Application Support/Blender/3.6/scripts/addons/CodeToCADBlenderAddon/BlenderProvider.py", line 576, in _createPrimitive
    BlenderActions.addPrimitive(
  File "/Users/techdragon/Library/Application Support/Blender/3.6/scripts/addons/CodeToCADBlenderAddon/BlenderActions.py", line 297, in addPrimitive
    assert blenderMesh == None, f"A mesh with name {primitiveName} already exists."
AssertionError: A mesh with name Cube already exists.
```

This mesh named Cube error appears for most of the examples when run in the Blender 3.6 LTS

**Comment by shehabattia96** [comment]
I assume you have the Default Cube loading into your scene, please use Delete Hierarchy to delete it (or delete the orphaned Cube mesh):
<img width="1067" alt="image" src="https://github.com/CodeToCAD/CodeToCAD/assets/15225337/1769f42b-a80d-45c3-833d-a0e185985ef8">


There is a similar issue where naming your cube "Cube" also triggers this. But in your case, please delete the Default Cube's mesh and it should work!

**Comment by shehabattia96** [comment]
@techdragon  I am adding a more helpful error message for the Default Cube situation. Does this look good?
```
"/Users/shehab/Desktop/projects/CodeToCAD/providers/blender/BlenderActions.py\", line 260, in blenderPrimitiveFunction\n    assert blenderMesh == None, f\"A mesh with name {primitiveName} already exists. {orphanMeshMessage}\"
AssertionError: A mesh with name Cube already exists. Your mesh is an orphan, please delete it.
If you are starting with the Default Cube, please remove it using Delete Hierarchy to delete both the object and the mesh, then try again.
```

**Comment by techdragon** [comment]
The issue I was having was that running the examples in an empty blender workspace/file seemed to throw the error when i expected it should instead create something.

**Comment by shehabattia96** [comment]
> in an empty blender workspace/file 

Could I ask you to check if there are orphaned meshes in your blender workspace? @techdragon 
1. Choose Outliner:
<img width="371" alt="image" src="https://github.com/CodeToCAD/CodeToCAD/assets/15225337/6694f137-4e0a-48bf-bb88-86e66027e45d">


2. Check if there are meshes under Meshes:
<img width="249" alt="image" src="https://github.com/CodeToCAD/CodeToCAD/assets/15225337/bf2c5794-7559-4869-ad73-2a87d864daff">

Thanks!

**Comment by shehabattia96** [comment]
Hey @techdragon, were you able to get the examples to work? I did a clean install and can't reproduce, so.. I still think it's the Default Cube mesh getting in your way!

**Comment by shehabattia96** [comment]
Closed the issue for inactivity and an open PR, feel free to reopen @techdragon. Thanks!
