### ISSUE TITLE
Blender Provider README is out of date

### ISSUE THREAD

**Issue by shehabattia96** [CodeToCAD/CodeToCAD#230]
The README instructions to set up Blender's Addon at https://github.com/CodeToCAD/CodeToCAD/tree/develop/providers/blender#running-codetocad

It should ask the user to download the zip file from the [Releases](https://github.com/CodeToCAD/CodeToCAD/releases) (https://github.com/CodeToCAD/CodeToCAD/releases) OR clone the repo and select the `blender_addon.py` file.

Edit: freezing working this issue because we need to add info for using the Launcher later.

**Comment by patchworquill** [comment]
I get an error trying to use the AddOn in Blender. After loading the blender_addon.py file, I have to select the CodeToCAD folder (following the YouTube tutorial video).

In Blender Preferences:
I selected the CodeToCAD root directory.
Then click "refresh" blender_provider. All good so far. 
<img width="664" alt="codetocad_preferences_dialog" src="https://github.com/CodeToCAD/CodeToCAD/assets/6552507/2fa7adfe-6e7e-4727-83a0-ccda53403c73">

From the blender tools menu (N) under CodeToCAD options, when I click "Reload CodeToCAD Module" I get an import error:

`ModuleNotFoundError: No module named codetocad.core.shapes.circle`

<img width="853" alt="codetocad_error_dialog" src="https://github.com/CodeToCAD/CodeToCAD/assets/6552507/68a09f06-c1ca-4fa4-8813-277ca2d3ef28">


When I manually navigate around the CodeToCAD repo, the codetocad/core/shape/circle.py exists, and contains the functions being complained about.

**Comment by shehabattia96** [comment]
Hey @patchworquill, thanks for the screenshots. Give me a minute I'll take a look.

In the meantime, could you try installing the addon from the zip file in releases? When you do this, you do not need to select the blender_addon.py file, it will do it automatically.

Please click the dropdown under Assets to see the zip file: https://github.com/CodeToCAD/CodeToCAD/releases: 
<img width="936" alt="image" src="https://github.com/CodeToCAD/CodeToCAD/assets/15225337/112c04e0-9384-4789-b698-4444fa9ec0aa">

**Comment by shehabattia96** [comment]
Just did a fresh install: I removed the addon -> quit blender -> imported `blender_addon.py` -> set the folder to my CodeToCAD repo root, and it seems to work fine:

<img width="807" alt="image" src="https://github.com/CodeToCAD/CodeToCAD/assets/15225337/1d5f0908-b0a8-4b32-bdc2-7f0820c81b64">


Could you please try the following?
1. Make sure the textbox in Blender's preferences actually points to CodeToCAD (and it's not like `CodeToCAD/some-other-nonsense`, there's a bug with Blender UI's file selector that appends stale file names to the end of the file url.
2. Try quitting Blender and then in the blender console try running `Part("myCube").create_cube("1m", "1m", "1m")` 

Thank you!

**Comment by shehabattia96** [comment]
#252 should resolve @patchworquill 's problem.
