### ISSUE TITLE
Add `black` to the project python dependencies, and make the pre-commit hook run `black .` to auto-format the code

### ISSUE THREAD

**Issue by shehabattia96** [CodeToCAD/CodeToCAD#255]
[Black](https://pypi.org/project/black/) is a code-formatter library. We use it to keep the code formatted and pass linting. We need to add this to the development pipeline.

Please add black to `/development/requirements.txt` and update `development/git_hooks/pre-commit.sh` to run `black .` before commiting.

**Comment by patchworquill** [comment]
Pushed to branch `bug/255-add-black-to-prehooks`

**Comment by shehabattia96** [comment]
Hey @patchworquill, I apologize, I didn't include very specific details in the original description.

I haven't tested this but, I think it should be `black "$ROOT_DIR"` because `black .` will run in the git hooks folder. I added `cd "$ROOT_DIR"` below. And when doing the code formatting, the formatted files will remain uncommited and not make it into the commit, so perhaps this may work, but I haven't run it:

```
#!/bin/sh

ROOT_DIR=`git rev-parse --show-toplevel`

cd "$ROOT_DIR"

set -e # exit if script errors.

echo "Running pre-commit hooks."

# MARK: format code
# references https://stackoverflow.com/a/38887400
EPOCH=timestamp-$(date +%s) 
STASH_RESULT=$(git stash save $EPOCH)
IS_STASH_SUCCESS=$(echo $STASH_RESULT|grep $EPOCH)

echo "Stashed changes (if any)"

black "$ROOT_DIR" # code formatting

git add -u

if [ "$IS_STASH_SUCCESS" ] then 
  echo "popping stash"
  git stash pop
fi

# Mark: run tests and lint checks:
sh "$ROOT_DIR/development/run_tests.sh"

sh "$ROOT_DIR/development/run_lint.sh"

echo "Done running pre-commit hooks."
```
