### ISSUE TITLE
Blender: one-direction extrude

### ISSUE THREAD

**Issue by shehabattia96** [CodeToCAD/CodeToCAD#298]
Blender's built-in extrude thickens the shape in two directions. We need a way to extrude in only one direction normal to a face.

**Comment by patchworquill** [comment]
Blender's docs on Extrude explain the behaviour and implementation in more detail for reference: https://docs.blender.org/manual/en/latest/modeling/meshes/editing/duplicating/extrude.html

This stackoverflow post has code for the API with a simple cube face extrusion example: https://stackoverflow.com/questions/37808840/selecting-a-face-and-extruding-a-cube-in-blender-via-python-api

**Comment by shehabattia96** [comment]
I was thinking a decent solution is to internally duplicate the face, translate it the extrude length along the normal vector, and loft the two surfaces using our existing loft method. The trickiest part here is to translate along the normal vector imo.

**Comment by patchworquill** [comment]
This thread has the formulas for calculating a normal based on the face data using vector crossproduct and vector subtraction: https://blenderartists.org/t/getting-face-normals-from-python/309648

It also seems you are correct that the API doesn't provide access to them...

**Comment by shehabattia96** [comment]
Nice find! Yah calculating from three points should be fine since 3 points define a plane. Thank you for looking into this :)

**Comment by shehabattia96** [comment]
@patchworquill Thanks for the reference, it helped! We can now project a face a certain distance away normal to another face. There is still a bug with rotated faces - I need to find the translation component due to rotation and add that to the translation vector before projecting it normal to the source face:
<img width="716" alt="image" src="https://github.com/CodeToCAD/CodeToCAD/assets/15225337/6783349d-81c8-4448-a5de-2fcda490d5a8">
