### ISSUE TITLE
ModuleNotFoundError: No module named 'codetocad.proxy'

### ISSUE THREAD

**Issue by Shrav108** [CodeToCAD/CodeToCAD#372]
I have installed codetocad using pip. But I get this error :
```
ModuleNotFoundError: No module named 'codetocad.proxy'
```

**Comment by shehabattia96** [comment]
Hey @Shrav108 , were you trying to run your script in Blender or Fusion360? Thanks!

**Comment by shehabattia96** [comment]
Actually I can reproduce your bug just via CLI. I'll look into it, thanks! You should still be able to run your scripts in Blender or Fusion360 though. The supported calls are highlighted in green or yellow: https://codetocad.github.io/CodeToCAD/docs.html?provider=Blender

```
% codetocad
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/codetocad", line 5, in <module>
    from codetocad.run import execute_launcher
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/codetocad/__init__.py", line 1, in <module>
    from codetocad.proxy import *
ModuleNotFoundError: No module named 'codetocad.proxy'
```

**Comment by Shrav108** [comment]
I am not using Blender or Fusion360. I am trying to use it with normal python script

**Comment by shehabattia96** [comment]
CLI tool fixed in https://github.com/CodeToCAD/CodeToCAD/pull/373, pushing a release soon.

**Comment by shehabattia96** [comment]
@Shrav108 , the new pip package should be up now. Please do `pip install -u codetocad` to grab the latest. Feel free to reopen the issue if you have any problems. Thanks!

**Comment by Shrav108** [comment]
Thank you for such a quick response 👍

**Comment by shehabattia96** [comment]
No problem, actually found another bug and pushed another release. It's going up now, thakns @Shrav108
