### ISSUE TITLE
KeyError: <class 'codetocad.interfaces.part_interface.PartInterface'> 

### ISSUE THREAD

**Issue by Shrav108** [CodeToCAD/CodeToCAD#378]
I was trying to use the ball_joint.py for getting started and encountered this error 
```
Cell In[5], line 1
----> 1 ball = Part("ball").create_sphere(1)
      2 ball_center = ball.get_landmark("center")  # or PresetLandmarks.center
      3 ball_bottom: LandmarkInterface = ball.get_landmark(PresetLandmark.bottom)  # or "bottom"

File C:\Users\Anaconda\anaconda3\Lib\site-packages\codetocad\proxy\part.py:68, in Part.__init__(self, name, description, native_instance)
     62 def __init__(
     63     self, name: "str", description: "str| None" = None, native_instance=None
     64 ):
     65     object.__setattr__(
     66         self,
     67         "__proxied",
---> 68         get_provider(PartInterface)(
     69             name, description, native_instance
     70         ),  # type: ignore
     71     )

File C:\Users\Anaconda\anaconda3\Lib\site-packages\codetocad\providers.py:11, in get_provider(interface)
      9 def get_provider(interface) -> type:
     10     global __providers
---> 11     return __providers[interface]

KeyError: <class 'codetocad.interfaces.part_interface.PartInterface'>
```

What to do ?

**Comment by shehabattia96** [comment]
This is the second bug I mentioned that I just fixed, it should be going up as soon as this pipeline finished, thanks! https://github.com/CodeToCAD/CodeToCAD/actions/runs/10617011418/job/29428785932

**Comment by shehabattia96** [comment]
It's done now, please try `pip install -U codetocad`, thanks!

**Comment by Shrav108** [comment]
It works. Thank you !

**Comment by Shrav108** [comment]
Problem still persists, even after update : 
```
KeyError                                  Traceback (most recent call last)
Cell In[13], line 1
----> 1 Part("Cube").create_cube(1, 1, 1)

File C:\Users\Anaconda\anaconda3\Lib\site-packages\codetocad\proxy\part.py:68, in Part.__init__(self, name, description, native_instance)
     62 def __init__(
     63     self, name: "str", description: "str| None" = None, native_instance=None
     64 ):
     65     object.__setattr__(
     66         self,
     67         "__proxied",
---> 68         get_provider(PartInterface)(
     69             name, description, native_instance
     70         ),  # type: ignore
     71     )

File C:\Users\Anaconda\anaconda3\Lib\site-packages\codetocad\providers.py:11, in get_provider(interface)
      9 def get_provider(interface) -> type:
     10     global __providers
---> 11     return __providers[interface]

KeyError: <class 'codetocad.interfaces.part_interface.PartInterface'>
```

**Comment by shehabattia96** [comment]
Hey @Shrav108, could you please post the file you're trying to run? Thank you

**Comment by Shrav108** [comment]
```
from codetocad import *
from codetocad.interfaces.landmark_interface import LandmarkInterface

Part("Cube").create_cube(1, 1, 1)
```

**Comment by shehabattia96** [comment]
Hey @Shrav108 , could you please double check that you have the latest pip version via `pip list | grep codetocad`? Or run `pip install -U codetocad` to get the latest. Thank you.

```
 % pip3 list | grep codetocad
     codetocad       0.4.1724941494
```

Forgive the bad whitespacing, I'll push a fix to that soon:
<img width="954" alt="image" src="https://github.com/user-attachments/assets/271bb563-9c22-44ea-a30e-e3f9a15c24a3">

**Comment by Shrav108** [comment]
I have pip - 24.2 and CodeToCad - 0.4.1724941494. I am using this in windows 11

**Comment by shehabattia96** [comment]
Interesting, we've seen some weird path import bugs on Windows in the past, so this could be related. I'll have to boot a Windows machine to find this bug. Please give me until tomorrow to get back to you. Thanks for opening an issue 👍

**Comment by shehabattia96** [comment]
@Shrav108 Unfortunately I couldn't reproduce your error on Windows. Could you please try reinstalling codetocad? `pip uninstall codetocad; pip install codetocad`, maybe upgrade is failing? Thanks!

<img width="1091" alt="image" src="https://github.com/user-attachments/assets/6316f292-7e37-4b41-be73-ef6c9e5ef15a">

**Comment by Shrav108** [comment]
I tried to run in a different environment, but seem to run into the same issue. My anaconda environment is in :
```C:/Users/Anaconda/anaconda/...```

instead of : 
```C:/Users/ComputerName/Anaconda/anaconda/...```

can this be the issue ?

**Comment by shehabattia96** [comment]
Hi @Shrav108, I'm not sure, I installed python 12 directly; not using conda. What `python --version` are you running? Thanks!

**Comment by Shrav108** [comment]
The error seems to be comming from this line in providers.py :
```
__providers = {}


def register(provider, interface):
    global __providers
    __providers[interface] = provider


def get_provider(interface) -> type:
    global __providers
    return __providers[interface]  // ERROR HERE
```
In part.py : 
```
    def __init__(
        self, name: "str", description: "str| None" = None, native_instance=None
    ):
        object.__setattr__(
            self,
            "__proxied",
            get_provider(PartInterface)(   #  ---> // CALL 
                name, description, native_instance
            ),  # type: ignore
        )
```
Error:
```

  File C:\Users\Anaconda\anaconda3\Lib\site-packages\codetocad\proxy\part.py:68 in __init__
    get_provider(PartInterface)(

  File C:\Users\Anaconda\anaconda3\Lib\site-packages\codetocad\providers.py:11 in get_provider
    return __providers[interface]

KeyError: <class 'codetocad.interfaces.part_interface.PartInterface'>
```

**Comment by shehabattia96** [comment]
@Shrav108 This error just means that the provider didn't register itself in the proxy service. Each provider has a `register()` method that it calls when it's loaded.
On the latest version, launchers/sample.py calls `register()`, it didn't use to do that before the fix. https://github.com/CodeToCAD/CodeToCAD/blob/develop/codetocad/launchers/sample.py#L11 

The only thing I can think of - happening to you - is that you have two or more different python versions running on your system, and when you did `pip install codetocad`the first time, it installed to one version, and the cli is registered to run the old one, so running `codetocad` in your terminal is pointing to an older version. And subsequent `pip install -u codetocad` is running on a different python version. Not really sure how you could resolve this other than to `python -m pip uninstall codetocad` on all your python versions on your system, and finally installing one on your python 12 instance.

Please let me know how I can help, happy to jump on a call to debug. If you're on Discord (you can find the link in the README) I can help there too in realtime. Thanks!

**Comment by shehabattia96** [comment]
Hey @Shrav108, I'm not sure if you were able to resolve your issue, but starting the latest release, you will be able to do `codetocad update` to automatically grab the latest version of the codetocad pip package: https://github.com/CodeToCAD/CodeToCAD/pull/380. If you have any issues, please reopen this ticket. Thanks!
